INSERT INTO Episodes (Title, Series, Doctor) VALUES
("Rose", 1, "Ninth"),
("The End of the World", 1, "Ninth"),
("The Unquiet Dead", 1, "Ninth"),
("Aliens of London", 1, "Ninth"),
("World War Three", 1, "Ninth"),
("Dalek", 1, "Ninth"),
("The Long Game", 1, "Ninth"),
("Father's Day", 1, "Ninth"),
("The Empty Child", 1, "Ninth"),
("The Doctor Dances", 1, "Ninth"),
("Boom Town", 1, "Ninth"),
("Bad Wolf", 1, "Ninth"),
("The Parting of the Ways ", 1, "Ninth"),
("The Christmas Invasion", 2, "Tenth"),
("New Earth", 2, "Tenth"),
("Tooth and Claw", 2, "Tenth"),
("School Reunion", 2, "Tenth"),
("The Girl in the Fireplace", 2, "Tenth"),
("Rise of the Cybermen", 2, "Tenth"),
("The Age of Steel", 2, "Tenth"),
("The Idiot's Lantern", 2, "Tenth"),
("The Impossible Planet", 2, "Tenth"),
("The Satan Pit", 2, "Tenth"),
("Love and Monsters", 2, "Tenth"),
("Fear Her", 2, "Tenth"),
("Army of Ghosts", 2, "Tenth"),
("Doomsday", 2, "Tenth"),
("The Runaway Bride", 3, "Tenth"),
("Smith and Jones", 3, "Tenth"),
("The Shakespeare Code", 3, "Tenth"),
("Gridlock", 3, "Tenth"),
("Daleks in Manhattan", 3, "Tenth"),
("Evolution of the Daleks", 3, "Tenth"),
("The Lazarus Experiment", 3, "Tenth"),
("42", 3, "Tenth"),
("Human Nature", 3, "Tenth"),
("Family of Blood", 3, "Tenth"),
("Blink", 3, "Tenth"),
("Utopia", 3, "Tenth"),
("The Sound of Drums", 3, "Tenth"),
("The Last of the Time Lords", 3, "Tenth"),
("Voyage of the Damned", 4, "Tenth"),
("Partners in Crime", 4, "Tenth"),
("The Fires of Pompeii", 4, "Tenth"),
("Planet of the Ood", 4, "Tenth"),
("The Sontaran Stratagem", 4, "Tenth"),
("The Poison Sky", 4, "Tenth"),
("The Doctor's Daughter", 4, "Tenth"),
("The Unicorn and the Wasp", 4, "Tenth"),
("Silence in the Library", 4, "Tenth"),
("Forest of the Dead", 4, "Tenth"),
("Midnight", 4, "Tenth"),
("Turn Left", 4, "Tenth"),
("The Stolen Earth", 4, "Tenth"),
("Journey's End", 4, "Tenth"),
("The Next Doctor", 4, "Tenth"),
("Planet of the Dead", 4, "Tenth"),
("The Waters of Mars", 4, "Tenth"),
("The End of Time Part One", 4, "Tenth"),
("The End of Time Part Two", 4, "Tenth"),
("The Eleventh Hour", 5, "Eleventh"),
("The Beast Below", 5, "Eleventh"),
("Victory of the Daleks", 5, "Eleventh"),
("The Time of Angels", 5, "Eleventh"),
("Flesh and Stone", 5, "Eleventh"),
("The Vampires of Venice", 5, "Eleventh"),
("Amy's Choice", 5, "Eleventh"),
("The Hungry Earth", 5, "Eleventh"),
("Cold Blood", 5, "Eleventh"),
("Vincent and the Doctor", 5, "Eleventh"),
("The Lodger", 5, "Eleventh"),
("The Pandorica Opens", 5, "Eleventh"),
("The Big Bang", 5, "Eleventh"),
("A Christmas Carol", 6, "Eleventh"),
("The Impossible Astronaut", 6, "Eleventh"),
("Day of the Moon", 6, "Eleventh"),
("The Curse of the Black Spot", 6, "Eleventh"),
("The Doctor's Wife", 6, "Eleventh"),
("The Rebel Flesh", 6, "Eleventh"),
("The Almost People", 6, "Eleventh"),
("A Good Man Goes to War", 6, "Eleventh"),
("Let's Kill Hitler", 6, "Eleventh"),
("Night Terrors", 6, "Eleventh"),
("The Girl Who Waited", 6, "Eleventh"),
("The God Complex", 6, "Eleventh"),
("Closing Time", 6, "Eleventh"),
("The Wedding of River Song", 6, "Eleventh"),
("The Doctor, The Widow, and the Wardrobe", 7, "Eleventh"),
("Asylum of the Daleks", 7, "Eleventh"),
("Dinosaurs on a Spaceship", 7, "Eleventh"),
("A Town Called Mercy", 7, "Eleventh"),
("The Power of Three", 7, "Eleventh"),
("The Angels Take Manhattan", 7, "Eleventh"),
("The Snowmen", 7, "Eleventh"),
("The Bells of Saint John", 7, "Eleventh"),
("The Rings of Akhaten", 7, "Eleventh"),
("Cold War", 7, "Eleventh"),
("Hide", 7, "Eleventh"),
("Journey to the Centre of the TARDIS", 7, "Eleventh"),
("The Crimson Horror", 7, "Eleventh"),
("Nightmare in Silver", 7, "Eleventh"),
("The Name of the Doctor", 7, "Eleventh"),
("The Day of the Doctor", 7, "Eleventh"),
("The Time of the Doctor", 7, "Eleventh"),
("Deep Breath", 8, "Twelfth"),
("Into the Dalek", 8, "Twelfth"),
("Robot of Sherwood", 8, "Twelfth"),
("Listen", 8, "Twelfth"),
("Time Heist", 8, "Twelfth"),
("The Caretaker", 8, "Twelfth"),
("Kill the Moon", 8, "Twelfth"),
("Mummy on the Orient Express", 8, "Twelfth"),
("Flatline", 8, "Twelfth"),
("In the Forest of the Night", 8, "Twelfth"),
("Dark Water", 8, "Twelfth"),
("Death in Heaven", 8, "Twelfth"),
("Last Christmas", 9, "Twelfth"),
("The Magician's Apprentice", 9, "Twelfth"),
("The Witch's Familiar", 9, "Twelfth"),
("Under the Lake", 9, "Twelfth"),
("Before the Flood", 9, "Twelfth"),
("The Girl Who Died", 9, "Twelfth"),
("The Woman Who Lived", 9, "Twelfth"),
("The Zygon Invasion", 9, "Twelfth"),
("The Zygon Inversion", 9, "Twelfth"),
("Sleep No More", 9, "Twelfth"),
("Face the Raven", 9, "Twelfth"),
("Heaven Sent", 9, "Twelfth"),
("Hell Bent", 9, "Twelfth"),
("The Husbands of River Song", 9, "Twelfth"),
("The Return of Doctor Mysterio", 10, "Twelfth"),
("The Pilot", 10, "Twelfth"),
("Smile", 10, "Twelfth"),
("Thin Ice", 10, "Twelfth"),
("Knock Knock", 10, "Twelfth"),
("Oxygen", 10, "Twelfth"),
("Extremis", 10, "Twelfth"),
("The Pyramid at the End of the World", 10, "Twelfth"),
("The Lie of the Land", 10, "Twelfth"),
("Empress of Mars", 10, "Twelfth"),
("The Eaters of Light", 10, "Twelfth"),
("World Enough and Time", 10, "Twelfth"),
("The Doctor Falls", 10, "Twelfth"),
("Twice Upon a Time", 10, "Twelfth"),
("The Woman Who Fell to Earth", 11, "Thirteenth"),
("The Ghost Monument", 11, "Thirteenth"),
("Rosa", 11, "Thirteenth"),
("Arachnids in the UK", 11, "Thirteenth"),
("The Tsuranga Conundrum", 11, "Thirteenth"),
("Demons of the Punjab", 11, "Thirteenth"),
("Kerblam!", 11, "Thirteenth"),
("The Witchfinders", 11, "Thirteenth"),
("It Takes You Away", 11, "Thirteenth"),
("The Battle of Ranskoor Av Kolos", 11, "Thirteenth"),
("Resolution", 11, "Thirteenth"),
("Spyfall, Part 1", 12, "Thirteenth"),
("Spyfall, Part 2", 12, "Thirteenth"),
("Orphan 55", 12, "Thirteenth"),
("Nikola Tesla's Night of Terror", 12, "Thirteenth"),
("Fugitive of the Judoon", 12, "Thirteenth"),
("Praxeus", 12, "Thirteenth"),
("Can You Hear Me?", 12, "Thirteenth"),
("The Haunting of Villa Diodati", 12, "Thirteenth"),
("Ascension of the Cybermen", 12, "Thirteenth"),
("The Timeless Children", 12, "Thirteenth"),
("Revolution of the Daleks", 12, "Thirteenth"),
("The Halloween Apocalypse", 13, "Thirteenth"),
("War of the Sontarans", 13, "Thirteenth"),
("Once, Upon Time", 13, "Thirteenth"),
("Village of the Angels", 13, "Thirteenth"),
("Survivors of the Flux", 13, "Thirteenth"),
("The Vanquishers", 13, "Thirteenth"),
("The Eve of the Daleks", 13, "Thirteenth"),
("Legend of the Sea Devils", 13, "Thirteenth");