const episodes = [
    { Title: "Rose", Series: 1, Doctor: "Ninth" },
    { Title: "The End of the World", Series: 1, Doctor: "Ninth" },
    { Title: "The Unquiet Dead", Series: 1, Doctor: "Ninth" },
    { Title: "Aliens of London", Series: 1, Doctor: "Ninth" },
    { Title: "World War Three", Series: 1, Doctor: "Ninth" },
    { Title: "Dalek", Series: 1, Doctor: "Ninth" },
    { Title: "The Long Game", Series: 1, Doctor: "Ninth" },
    { Title: "Father's Day", Series: 1, Doctor: "Ninth" },
    { Title: "The Empty Child", Series: 1, Doctor: "Ninth" },
    { Title: "The Doctor Dances", Series: 1, Doctor: "Ninth" },
    { Title: "Boom Town", Series: 1, Doctor: "Ninth" },
    { Title: "Bad Wolf", Series: 1, Doctor: "Ninth" },
    { Title: "The Parting of the Ways ", Series: 1, Doctor: "Ninth" },
    { Title: "The Christmas Invasion", Series: 2, Doctor: "Tenth" },
    { Title: "New Earth", Series: 2, Doctor: "Tenth" },
    { Title: "Tooth and Claw", Series: 2, Doctor: "Tenth" },
    { Title: "School Reunion", Series: 2, Doctor: "Tenth" },
    { Title: "The Girl in the Fireplace", Series: 2, Doctor: "Tenth" },
    { Title: "Rise of the Cybermen", Series: 2, Doctor: "Tenth" },
    { Title: "The Age of Steel", Series: 2, Doctor: "Tenth" },
    { Title: "The Idiot's Lantern", Series: 2, Doctor: "Tenth" },
    { Title: "The Impossible Planet", Series: 2, Doctor: "Tenth" },
    { Title: "The Satan Pit", Series: 2, Doctor: "Tenth" },
    { Title: "Love and Monsters", Series: 2, Doctor: "Tenth" },
    { Title: "Fear Her", Series: 2, Doctor: "Tenth" },
    { Title: "Fear Her", Series: 2, Doctor: "Tenth" },
    { Title: "Army of Ghosts", Series: 2, Doctor: "Tenth" },
    { Title: "Doomsday", Series: 2, Doctor: "Tenth" },
    { Title: "The Runaway Bride", Series: 3, Doctor: "Tenth" },
    { Title: "Smith and Jones", Series: 3, Doctor: "Tenth" },
    { Title: "The Shakespeare Code", Series: 3, Doctor: "Tenth" },
    { Title: "Gridlock", Series: 3, Doctor: "Tenth" },
    { Title: "Daleks in Manhattan", Series: 3, Doctor: "Tenth" },
    { Title: "Evolution of the Daleks", Series: 3, Doctor: "Tenth" },
    { Title: "The Lazarus Experiment", Series: 3, Doctor: "Tenth" },
    { Title: "42", Series: 3, Doctor: "Tenth" },
    { Title: "Human Nature", Series: 3, Doctor: "Tenth" },
    { Title: "Family of Blood", Series: 3, Doctor: "Tenth" },
    { Title: "Blink", Series: 3, Doctor: "Tenth" },
    { Title: "Utopia", Series: 3, Doctor: "Tenth" },
    { Title: "The Sound of Drums", Series: 3, Doctor: "Tenth" },
    { Title: "The Last of the Time Lords", Series: 3, Doctor: "Tenth" },
    { Title: "Voyage of the Damned", Series: 4, Doctor: "Tenth" },
    { Title: "Partners in Crime", Series: 4, Doctor: "Tenth" },
    { Title: "The Fires of Pompeii", Series: 4, Doctor: "Tenth" },
    { Title: "Planet of the Ood", Series: 4, Doctor: "Tenth" },
    { Title: "The Sontaran Stratagem", Series: 4, Doctor: "Tenth" },
    { Title: "The Poison Sky", Series: 4, Doctor: "Tenth" },
    { Title: "The Doctor's Daughter", Series: 4, Doctor: "Tenth" },
    { Title: "The Unicorn and the Wasp", Series: 4, Doctor: "Tenth" },
    { Title: "Silence in the Library", Series: 4, Doctor: "Tenth" },
    { Title: "Forest of the Dead", Series: 4, Doctor: "Tenth" },
    { Title: "Midnight", Series: 4, Doctor: "Tenth" },
    { Title: "Turn Left", Series: 4, Doctor: "Tenth" },
    { Title: "The Stolen Earth", Series: 4, Doctor: "Tenth" },
    { Title: "Journey's End", Series: 4, Doctor: "Tenth" },
    { Title: "The Next Doctor", Series: 4, Doctor: "Tenth" },
    { Title: "Planet of the Dead", Series: 4, Doctor: "Tenth" },
    { Title: "The Waters of Mars", Series: 4, Doctor: "Tenth" },
    { Title: "The End of Time Part One", Series: 4, Doctor: "Tenth" },
    { Title: "The End of Time Part Two", Series: 4, Doctor: "Tenth" },
    { Title: "The Eleventh Hour", Series: 5, Doctor: "Eleventh" },
    { Title: "The Beast Below", Series: 5, Doctor: "Eleventh" },
    { Title: "Victory of the Daleks", Series: 5, Doctor: "Eleventh" },
    { Title: "The Time of Angels", Series: 5, Doctor: "Eleventh" },
    { Title: "Flesh and Stone", Series: 5, Doctor: "Eleventh" },
    { Title: "The Vampires of Venice", Series: 5, Doctor: "Eleventh" },
    { Title: "Amy's Choice", Series: 5, Doctor: "Eleventh" },
    { Title: "The Hungry Earth", Series: 5, Doctor: "Eleventh" },
    { Title: "Cold Blood", Series: 5, Doctor: "Eleventh" },
    { Title: "Vincent and the Doctor", Series: 5, Doctor: "Eleventh" },
    { Title: "The Lodger", Series: 5, Doctor: "Eleventh" },
    { Title: "The Pandorica Opens", Series: 5, Doctor: "Eleventh" },
    { Title: "The Big Bang", Series: 5, Doctor: "Eleventh" },
    { Title: "A Christmas Carol", Series: 6, Doctor: "Eleventh" },
    { Title: "The Impossible Astronaut", Series: 6, Doctor: "Eleventh" },
    { Title: "Day of the Moon", Series: 6, Doctor: "Eleventh" },
    { Title: "The Curse of the Black Spot", Series: 6, Doctor: "Eleventh" },
    { Title: "The Doctor's Wife", Series: 6, Doctor: "Eleventh" },
    { Title: "The Rebel Flesh", Series: 6, Doctor: "Eleventh" },
    { Title: "The Almost People", Series: 6, Doctor: "Eleventh" },
    { Title: "A Good Man Goes to War", Series: 6, Doctor: "Eleventh" },
    { Title: "Let's Kill Hitler", Series: 6, Doctor: "Eleventh" },
    { Title: "Night Terrors", Series: 6, Doctor: "Eleventh" },
    { Title: "The Girl Who Waited", Series: 6, Doctor: "Eleventh" },
    { Title: "The God Complex", Series: 6, Doctor: "Eleventh" },
    { Title: "Closing Time", Series: 6, Doctor: "Eleventh" },
    { Title: "The Wedding of River Song", Series: 6, Doctor: "Eleventh" },
    { Title: "The Doctor, The Widow, and the Wardrobe", Series: 7, Doctor: "Eleventh" },
    { Title: "Asylum of the Daleks", Series: 7, Doctor: "Eleventh" },
    { Title: "Dinosaurs on a Spaceship", Series: 7, Doctor: "Eleventh" },
    { Title: "A Town Called Mercy", Series: 7, Doctor: "Eleventh" },
    { Title: "The Power of Three", Series: 7, Doctor: "Eleventh" },
    { Title: "The Angels Take Manhattan", Series: 7, Doctor: "Eleventh" },
    { Title: "The Snowmen", Series: 7, Doctor: "Eleventh" },
    { Title: "The Bells of Saint John", Series: 7, Doctor: "Eleventh" },
    { Title: "The Rings of Akhaten", Series: 7, Doctor: "Eleventh" },
    { Title: "Cold War", Series: 7, Doctor: "Eleventh" },
    { Title: "Hide", Series: 7, Doctor: "Eleventh" },
    { Title: "Journey to the Centre of the TARDIS", Series: 7, Doctor: "Eleventh" },
    { Title: "The Crimson Horror", Series: 7, Doctor: "Eleventh" },
    { Title: "Nightmare in Silver", Series: 7, Doctor: "Eleventh" },
    { Title: "The Name of the Doctor", Series: 7, Doctor: "Eleventh" },
    { Title: "The Day of the Doctor", Series: 7, Doctor: "Eleventh" },
    { Title: "The Time of the Doctor", Series: 7, Doctor: "Eleventh" },
    { Title: "Deep Breath", Series: 8, Doctor: "Twelfth" },
    { Title: "Into the Dalek", Series: 8, Doctor: "Twelfth" },
    { Title: "Robot of Sherwood", Series: 8, Doctor: "Twelfth" },
    { Title: "Listen", Series: 8, Doctor: "Twelfth" },
    { Title: "Time Heist", Series: 8, Doctor: "Twelfth" },
    { Title: "The Caretaker", Series: 8, Doctor: "Twelfth" },
    { Title: "Kill the Moon", Series: 8, Doctor: "Twelfth" },
    { Title: "Mummy on the Orient Express", Series: 8, Doctor: "Twelfth" },
    { Title: "Flatline", Series: 8, Doctor: "Twelfth" },
    { Title: "In the Forest of the Night", Series: 8, Doctor: "Twelfth" },
    { Title: "Dark Water", Series: 8, Doctor: "Twelfth" },
    { Title: "Death in Heaven", Series: 8, Doctor: "Twelfth" },
    { Title: "Last Christmas", Series: 9, Doctor: "Twelfth" },
    { Title: "The Magician's Apprentice", Series: 9, Doctor: "Twelfth" },
    { Title: "The Witch's Familiar", Series: 9, Doctor: "Twelfth" },
    { Title: "Under the Lake", Series: 9, Doctor: "Twelfth" },
    { Title: "Before the Flood", Series: 9, Doctor: "Twelfth" },
    { Title: "The Girl Who Died", Series: 9, Doctor: "Twelfth" },
    { Title: "The Woman Who Lived", Series: 9, Doctor: "Twelfth" },
    { Title: "The Zygon Invasion", Series: 9, Doctor: "Twelfth" },
    { Title: "The Zygon Inversion", Series: 9, Doctor: "Twelfth" },
    { Title: "Sleep No More", Series: 9, Doctor: "Twelfth" },
    { Title: "Face the Raven", Series: 9, Doctor: "Twelfth" },
    { Title: "Heaven Sent", Series: 9, Doctor: "Twelfth" },
    { Title: "Hell Bent", Series: 9, Doctor: "Twelfth" },
    { Title: "The Husbands of River Song", Series: 9, Doctor: "Twelfth" },
    { Title: "The Return of Doctor Mysterio", Series: 10, Doctor: "Twelfth" },
    { Title: "The Pilot", Series: 10, Doctor: "Twelfth" },
    { Title: "Smile", Series: 10, Doctor: "Twelfth" },
    { Title: "Thin Ice", Series: 10, Doctor: "Twelfth" },
    { Title: "Knock Knock", Series: 10, Doctor: "Twelfth" },
    { Title: "Oxygen", Series: 10, Doctor: "Twelfth" },
    { Title: "Extremis", Series: 10, Doctor: "Twelfth" },
    { Title: "The Pyramid at the End of the World", Series: 10, Doctor: "Twelfth" },
    { Title: "The Lie of the Land", Series: 10, Doctor: "Twelfth" },
    { Title: "Empress of Mars", Series: 10, Doctor: "Twelfth" },
    { Title: "The Eaters of Light", Series: 10, Doctor: "Twelfth" },
    { Title: "World Enough and Time", Series: 10, Doctor: "Twelfth" },
    { Title: "The Doctor Falls", Series: 10, Doctor: "Twelfth" },
    { Title: "Twice Upon a Time", Series: 10, Doctor: "Twelfth" },
    { Title: "The Woman Who Fell to Earth", Series: 11, Doctor: "Thirteenth" },
    { Title: "The Ghost Monument", Series: 11, Doctor: "Thirteenth" },
    { Title: "Rosa", Series: 11, Doctor: "Thirteenth" },
    { Title: "Arachnids in the UK", Series: 11, Doctor: "Thirteenth" },
    { Title: "The Tsuranga Conundrum", Series: 11, Doctor: "Thirteenth" },
    { Title: "Demons of the Punjab", Series: 11, Doctor: "Thirteenth" },
    { Title: "Kerblam!", Series: 11, Doctor: "Thirteenth" },
    { Title: "The Witchfinders", Series: 11, Doctor: "Thirteenth" },
    { Title: "It Takes You Away", Series: 11, Doctor: "Thirteenth" },
    { Title: "The Battle of Ranskoor Av Kolos", Series: 11, Doctor: "Thirteenth" },
    { Title: "Resolution", Series: 11, Doctor: "Thirteenth" },
    { Title: "Spyfall, Part 1", Series: 12, Doctor: "Thirteenth" },
    { Title: "Spyfall, Part 2", Series: 12, Doctor: "Thirteenth" },
    { Title: "Orphan 55", Series: 12, Doctor: "Thirteenth" },
    { Title: "Nikola Tesla's Night of Terror", Series: 12, Doctor: "Thirteenth" },
    { Title: "Fugitive of the Judoon", Series: 12, Doctor: "Thirteenth" },
    { Title: "Praxeus", Series: 12, Doctor: "Thirteenth" },
    { Title: "Can You Hear Me?", Series: 12, Doctor: "Thirteenth" },
    { Title: "The Haunting of Villa Diodati", Series: 12, Doctor: "Thirteenth" },
    { Title: "Ascension of the Cybermen", Series: 12, Doctor: "Thirteenth" },
    { Title: "The Timeless Children", Series: 12, Doctor: "Thirteenth" },
    { Title: "Revolution of the Daleks", Series: 12, Doctor: "Thirteenth" },
    { Title: "The Halloween Apocalypse", Series: 13, Doctor: "Thirteenth" },
    { Title: "War of the Sontarans", Series: 13, Doctor: "Thirteenth" },
    { Title: "Once, Upon Time", Series: 13, Doctor: "Thirteenth" },
    { Title: "Village of the Angels", Series: 13, Doctor: "Thirteenth" },
    { Title: "Survivors of the Flux", Series: 13, Doctor: "Thirteenth" },
    { Title: "The Vanquishers", Series: 13, Doctor: "Thirteenth" },
    { Title: "The Eve of the Daleks", Series: 13, Doctor: "Thirteenth" },
    { Title: "Legend of the Sea Devils", Series: 13, Doctor: "Thirteenth" }
];

module.exports = episodes;